'feature':
  - 'feature/*'
'enhancement':
  - 'feature/*'
'bug':
  - 'fix/*'
'fix':
  - 'fix/*'
'hotfix':
  - 'hotfix/*'
'urgent':
  - 'hotfix/*'
'priority:high':
  - 'hotfix/*'
'release':
  - 'release/*'
'documentation':
  - 'docs/*'
'maintenance':
  - 'chore/*'
'dependencies':
  - 'chore/*'
'testing':
  - 'test/*'
